# Generated by Django 4.2.5 on 2024-05-20 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('first_name', models.CharField(max_length=200, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('occasion', models.CharField(max_length=200, verbose_name='Повод')),
                ('description', models.TextField(verbose_name='Описание')),
                ('target', models.IntegerField(blank=True, default=0, verbose_name='Цель')),
                ('image', models.ImageField(blank=True, upload_to='media/', verbose_name='Изображение')),
                ('collection_period', models.DateField(verbose_name='Срок сбора')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Сбор',
                'verbose_name_plural': 'Сборы',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_payment', models.CharField(choices=[('Единоразовое пожертвование', 'Единоразовое пожертвование'), ('Многоразовое пожертвование', 'Многоразовое пожертвование')], max_length=200, verbose_name='Тип пожертвования')),
                ('sum_payment', models.IntegerField(verbose_name='Сумма пожертвования')),
                ('first_name', models.CharField(max_length=200, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата пожертвования')),
                ('is_show', models.BooleanField(default=True, verbose_name='Показывать')),
                ('collect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='collect.collect', verbose_name='Сбор')),
            ],
            options={
                'verbose_name': 'Пожертвование',
                'verbose_name_plural': 'Пожертвования',
            },
        ),
    ]
